server {
  listen 80;

  client_max_body_size 10m;
  root /home/isucon/private_isu/webapp/public;

  location /image/ {
    root /home/isucon/private_isu/webapp/public;
    try_files $uri =404;
  }

  location / {
    proxy_set_header Host $host;
    proxy_pass http://127.0.0.1:8080;
  }
}
